# Run all notebooks on every push
name: Notebooks
on:
  push:
    branches: [ \#210_David ]
jobs:
  run:
    runs-on: ubuntu-latest
    name: Run treebeard
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: treebeardtech/treebeard@master
        notebooks: "examples/*ipynb"
