# Run all notebooks on every push
name: Notebooks
on:
  push:
    branches: [ \#210_David ]
jobs:
  run:
    runs-on: ubuntu-latest
    name: Run treebeard
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - uses: treebeardtech/treebeard@master
        with:
          use-docker: false
